# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    npm run test:coverage
  displayName: 'npm test'
  continueOnError: true

- script: |
    npm run build
  displayName: 'npm build'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Publish Test Results'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    failIfCoverageEmpty: true
  condition: succeededOrFailed() 

- task: PublishPipelineArtifact@1
  displayName: 'Publish build artifacts'
  inputs:
    targetPath: '$(Pipeline.Workspace)/dist/'
    artifact: 'nextech-ai-scribe-sdk'
    publishLocation: 'pipeline'
